spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cleaningapp_db
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

jwt:
  secret: <ВАШ Base64-закодированный 32+-байтный секрет>
  expiration-ms: 3600000

app:
  upload:
    dir: ./uploads

logging:
  level:
    org.springframework: INFO
    com.example.cleaningapp.server: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
