spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cleaningapp_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8888

jwt:
  secret: xpbJdhpK9WQYBOstZ5+3dhYW+iu/dri8OPCSZX8dsuo=
  expiration-ms: 3600000

app:
  upload:
    dir: ./uploads

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

logging:
  level:
    org.springframework: INFO
    com.example.cleaningapp.server: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
