spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cleaningapp_db
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none        # миграции будет делать Liquibase, не Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    # Если хотите хранить логи о миграциях в отдельной таблице:
    # contexts: development, production

server:
  port: 8080

# JWT settings
jwt:
  secret: yourSuperSecretJwtKeyHere  # поменяйте на сложный ключ, загружайте из переменных окружения
  expiration-ms: 3600000             # 1 час в миллисекундах

# Путь для хранения загруженных файлов (папка на диске)
app:
  upload:
    dir: ./uploads

logging:
  level:
    org.springframework: INFO
    com.example.cleaningapp.server: DEBUG   # чтобы видеть свои логи

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
